import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const satoshi = localFont({
  src:[
    {
      path: './fonts/Satoshi-Regular.otf'
    },
    {
      path: './fonts/Satoshi-Black.otf'
    },
    // {
    //   path: './fonts/Satoshi-BlackItalic.otf'
    // },
    {
      path: './fonts/Satoshi-Bold.otf'
    },
    // {
    //   path: './fonts/Satoshi-BoldItalic.otf'
    // },
    // {
    //   path: './fonts/Satoshi-Italic.otf'
    // },
    {
      path: './fonts/Satoshi-Light.otf'
    },
    // {
    //   path: './fonts/Satoshi-LightItalic.otf'
    // },
    {
      path: './fonts/Satoshi-Medium.otf'
    },
    // {
    //   path: './fonts/Satoshi-MediumItalic.otf'
    // },
  ]
})


export const metadata: Metadata = {
  title: "Seep: A Tech Innovative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}><Navbar/><div className="mt-24">{children}</div><Footer/></body>
    </html>
  );
}
